---
- name: Update and reboot servers
  hosts: all
  become: true
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
